name: Download M3U8 Stream

on:
  repository_dispatch:
    types: [download-m3u8]
    
jobs:
  download:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yt-dlp
          
      - name: Download M3U8 stream
        run: |
          mkdir -p downloads
          yt-dlp -o "downloads/%(title)s.%(ext)s" "${{ github.event.client_payload.url }}"
          
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ github.event.client_payload.name || 'video-recording' }}
          path: downloads/
          retention-days: 7 